# Generated by Django 3.2.10 on 2023-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
