# Generated by Django 3.2.10 on 2023-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Frontendapp', '0002_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
