# Generated by Django 3.2.10 on 2023-07-24 07:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Frontendapp', '0003_cartdb_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdb',
            name='Total_Price',
        ),
    ]
