# Generated by Django 3.2.10 on 2023-07-21 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Backendapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartdb',
        ),
    ]
